Since LMSIR is relevant for both malignancy prediction in non-masses (see T2_featureRelevance) and predictive of T2wBIRADSRSI
======
```{r set-options, echo=FALSE, cache=FALSE}
options(width =250)
```

```{r}
require(ggplot2)
library("RSQLite")
setwd("Z:/Cristina/MassNonmass/Section 2 - Experiments/featureRelevance")
```

```{r fig.width=10, fig.height=12}
read_T2data <- function(subdata) {
  sqlite <- dbDriver("SQLite")
  conn <- dbConnect(sqlite, "stage1T2updatedFeatures.db")
  
  # 2) all T1W features
  lesionsQuery <- dbGetQuery(conn, "SELECT *
           FROM  stage1features
           INNER JOIN lesion ON (stage1features.lesion_id = lesion.lesion_id)
           INNER JOIN f_T2 ON (stage1features.lesion_id = f_T2.lesion_id)")
  
  # prune entries and extract feature subsets
  # corresponds to 5 entries lesion info, 34 dynamic, 19 morpho, 34 texture fueatures
  lesionfields =  names(lesionsQuery)
  lesioninfo = lesionsQuery[c(2,130,130:154)]
  T2info = lesionsQuery[c(155:202)]
  T2features = lesionsQuery[c(156,153,157,165:166,168:202,104:123)]
  
  T2features$lesion_label <- as.factor(T2features$lesion_label)
  summary(T2features$lesion_label)
 
    
  if(subdata=="mass"){
    # organized the data by subdata
    M<-subset(T2features, lesion_label=="massB" | lesion_label=="massM")
    ifelse( M$lesion_label == "massB", "NC", "C") -> M$lesion_label
    T2features = M
    
  }
  if(subdata=="nonmass"){
    # organized the data by subdata
    N<-subset(T2features, lesion_label=="nonmassB" | lesion_label=="nonmassM")
    ifelse( N$lesion_label == "nonmassB", "NC", "C") -> N$lesion_label
    T2features = N
    
  }
  if(subdata=="stage1"){
    # organized the data by subdata
    M<-subset(T2features, lesion_label=="massB" | lesion_label=="massM")
    ifelse( M$lesion_label == "massB", "mass", "mass") -> M$lesion_label
    N<-subset(T2features, lesion_label=="nonmassB" | lesion_label=="nonmassM")
    ifelse( N$lesion_label == "nonmassB", "nonmass", "nonmass") -> N$lesion_label
    T2features = data.frame(rbind(M,N)) 

  }
  
  # procees data
  T2features$lesion_label <- as.factor(T2features$lesion_label)

  return(T2features)
}

```


What features are most predictive of LMSIR (for a predictive regressor)?
==================
```{r}
# format datasets for inquiring predictive power for LMSIR
T2allfeatures = read_T2data(subdata = "all")
T2allfeatures$origlesion_label = T2allfeatures$lesion_label
T2features_LMSIR = na.omit(cbind(T2allfeatures[6], T2allfeatures[-6][4:ncol(T2allfeatures)-1]))

# Random Forest feature relevance
library("Boruta")
set.seed(1)
LMSIR_Boruta <- Boruta(LMSIR ~ . - origlesion_label, data = T2features_LMSIR, 
    doTrace = 2, ntree = 1000)
print(LMSIR_Boruta)

library("caret")
confirmedT2_LMSIR <- LMSIR_Boruta$finalDecision[LMSIR_Boruta$finalDecision == 
    "Confirmed"]
tentativeT2_LMSIR <- LMSIR_Boruta$finalDecision[LMSIR_Boruta$finalDecision == 
    "Tentative"]
allT2_LMSIR = T2features_LMSIR[c(names(confirmedT2_LMSIR), names(tentativeT2_LMSIR))]

super.sym <- trellis.par.get("superpose.symbol")
## plot for masses
splom(~T2features_LMSIR[c(names(confirmedT2_LMSIR))], groups = origlesion_label, 
    data = T2features_LMSIR, panel = panel.superpose, key = list(title = "T2 relevant LMSIR features", 
        columns = 4, points = list(pch = super.sym$pch[1:4], col = super.sym$col[1:4], 
            fill = super.sym$col[1:4]), text = list(c("massB", "massM", "nonmassB", 
            "nonmassM"))))


# Now plot z-scores
rankings_LMSIR <- LMSIR_Boruta$ImpHistory

LMSIRframezscore_selected = {
}
# proces HyperHypo = 7
for (i in 1:length(allT2_LMSIR)) {
    cfeature = as.data.frame(allT2_LMSIR[i])
    LMSIRframe = data.frame(zscores = rankings_LMSIR[, colnames(cfeature)])
    LMSIRframe$MorN = "LMSIR"
    LMSIRframe$feature = colnames(cfeature)
    LMSIRframezscore_selected <- rbind(LMSIRframezscore_selected, LMSIRframe)
}

# add shadow mean
LMSIRframe = data.frame(zscores = rankings_LMSIR[, "shadowMean"])
LMSIRframe$MorN = "LMSIR"
LMSIRframe$feature = "shadowMean"
LMSIRframezscore_selected <- rbind(LMSIRframezscore_selected, LMSIRframe)

# plot for predicting Hyper vs. Hypo
p <- ggplot(LMSIRframezscore_selected, aes(factor(feature), zscores, fill = factor(MorN)))
p + geom_boxplot() + coord_flip() + labs(title = "most predictive features for LMSIR")

```

```{r}
save.image("Z:/Cristina/MassNonmass/Section 2 - Experiments/featureRelevance/Rdata/T2_featurespred_LMSIR.RData")
```

